### ISSUE TITLE
Using --git and --version latest fails

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/gpg-build-scripts#10]
For example (using libgpg-error,  though this may apply to other components):
`./install_gpg_component.sh --component libgpg-error --version latest --git [...]'`

Will fail because it will attempt to do this:
```
pushd libgpg-error-git-1.32
git checkout 1.32
```

But libgpg-error tags are actually of the form `libgpg-error-1.32`.

**Comment by skalee** [comment]
@dewyatt, when working with git sources, you should rather try "master" (or name other git ref) instead of "latest", as in `./install_gpg_component.sh --component libgpg-error --version master --git [...]`. Also, see following:

https://github.com/riboseinc/gpg-build-scripts/blob/a66ddd513c539798c2385d00c1ff566d1ff4e0b5/install_gpg_component.sh#L34-L37

Sorry for late answer.

**Comment by dewyatt** [comment]
@skalee Makes sense to me! Maybe a case of RTFM here. :)
